# Generated by Django 4.0.5 on 2022-06-21 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('petsitters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsitter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
