# Generated by Django 4.0.5 on 2022-06-28 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_code',
            new_name='code',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to='users.user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='nickname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_nickname', to='users.user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('in_progress', 'In_Progress'), ('deleted', 'Deleted')], default='in_draft', max_length=30),
        ),
    ]
