# Generated by Django 4.0.5 on 2022-06-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_booking_code_booking_code_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
